-- migrations/2026-09-14-mtg-target-schema-and-backfill.sql
-- ============================================================================
-- MTGPrices Stage 1A — legacy rename + clean-start production schema.
-- ============================================================================
--
-- This migration produces the following end state:
--
--   LEGACY / ARCHIVE TABLES (renamed, contents preserved byte-for-byte):
--     mtg_sets_legacy_20260327          ← was mtg_sets            (1,029 rows)
--     mtg_cards_legacy_20260327         ← was mtg_cards           (104,505 rows)
--     mtg_daily_prices_legacy_20260327  ← was mtg_daily_prices    (98,250 rows)
--     mtg_card_trends_legacy_20260327   ← was mtg_card_trends     (0 rows)
--
--   NEW PRODUCTION TABLES (empty; canonical model for Stage 1B onwards):
--     mtg_sets                      canonical Scryfall set catalogue
--       └── mtg_printings           one row per Scryfall printing
--             └── mtg_printing_finishes  (nonfoil / foil / etched / …)
--                   └── mtg_price_observations   append-only daily rows
--     mtg_oracle_cards              game-rules card identity
--     mtg_oracle_legalities         normalised per-format legality
--     mtg_rulings                   authoritative rulings
--     mtg_external_identifiers      MTGJSON UUID / TCGplayer / Cardmarket
--
-- Rename safety:
--   * PostgreSQL tracks foreign keys by internal OID, not by table
--     name, so the two intra-legacy FKs
--       mtg_card_trends.card_id → mtg_cards.id
--       mtg_daily_prices.card_id → mtg_cards.id
--     continue to work automatically after the rename.
--   * A dependency probe on 2026-09-14 confirmed zero external
--     FKs into any legacy MTG table, zero views/materialised
--     views derived from them, and zero RPCs referencing them.
--     Application code contains no references to the legacy
--     table names outside audit/migrate probe scripts.
--   * The rename is idempotent via DO-blocks: if a legacy table
--     has already been renamed, the block is a no-op on that
--     table.
--
-- Design choices for the NEW production tables:
--   * Every row has an internal UUID primary key generated by
--     gen_random_uuid(). External identifiers (Scryfall printing
--     UUID, Scryfall set UUID, Scryfall oracle_id, MTGJSON UUID,
--     etc.) are stored as separate UNIQUE columns and are NEVER
--     used as the primary key. This decouples MTGPrices identity
--     from provider-side identity.
--   * mtg_printings authoritatively links to a set via
--       mtg_printings.set_id UUID NOT NULL REFERENCES mtg_sets(id).
--     A denormalised mtg_printings.set_code TEXT is retained
--     purely for human debugging + queries against external
--     callers who only know the Scryfall code. The relational
--     source of truth is set_id.
--   * pgcrypto is required (mtg_rulings.comment_hash uses
--     digest(comment, 'sha256')). The migration creates the
--     extension defensively and asserts digest() is callable
--     via a DO PERFORM block before any dependent DDL runs.
--   * mtg_price_observations column semantics (kept from the
--     already-approved MTGJSON-compatible design):
--       provider          = underlying pricing provider /
--                           marketplace (tcgplayer, cardmarket,
--                           cardkingdom, cardhoarder, scryfall, …)
--       ingestion_source  = delivery / parsing pipeline
--                           (mtgjson_all_prices, mtgjson_all_prices_today,
--                            scryfall_bulk, …)
--       market            = paper | mtgo | arena | …
--       price_type        = retail | buylist | market | low | …
--       finish            = via printing_finish_id → mtg_printing_finishes
--       currency          = USD | EUR | TIX | …
--       condition         = optional NM/LP/… when the provider quotes
--                           per condition; NULL when unqualified.
--
-- Data movement:
--   Zero rows are inserted into the new production tables. All
--   eight new tables (mtg_sets + 7 downstream) are expected to
--   remain empty until Stage 1B (fresh Scryfall ingestion) and
--   Stage 1C (fresh MTGJSON ingestion) populate them.
--
-- Idempotency:
--   * DO-block-guarded ALTER TABLE … RENAME operations.
--   * CREATE EXTENSION IF NOT EXISTS.
--   * CREATE TABLE IF NOT EXISTS.
--   * CREATE (UNIQUE) INDEX IF NOT EXISTS.
--   * DROP POLICY IF EXISTS + CREATE POLICY.
--
-- Transactionality:
--   Whole file in one BEGIN … COMMIT. Supabase SQL Editor also
--   wraps pastes in a transaction; the explicit BEGIN is for
--   review clarity.
--
-- ============================================================================

BEGIN;

-- ─── Extension + digest() assertion ─────────────────────────────────────────
-- mtg_rulings.comment_hash uses digest(comment, 'sha256'). Ensure the
-- extension is installed AND callable before creating that table.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  -- Will raise `function digest(...) does not exist` if pgcrypto is
  -- somehow unavailable, causing the whole transaction to abort
  -- cleanly instead of later while creating mtg_rulings.
  PERFORM digest('probe', 'sha256');
END $$;

-- ─── Rename the four legacy MTG tables ──────────────────────────────────────
-- Idempotent: each DO block renames the table only if the ORIGINAL name
-- still exists AND the archive name does not yet exist. A re-apply of this
-- migration after Stage 1B has populated new mtg_sets is safe: none of
-- these branches fire.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_sets')
     AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_sets_legacy_20260327')
  THEN
    EXECUTE 'ALTER TABLE public.mtg_sets RENAME TO mtg_sets_legacy_20260327';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_cards')
     AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_cards_legacy_20260327')
  THEN
    EXECUTE 'ALTER TABLE public.mtg_cards RENAME TO mtg_cards_legacy_20260327';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_daily_prices')
     AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_daily_prices_legacy_20260327')
  THEN
    EXECUTE 'ALTER TABLE public.mtg_daily_prices RENAME TO mtg_daily_prices_legacy_20260327';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_card_trends')
     AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mtg_card_trends_legacy_20260327')
  THEN
    EXECUTE 'ALTER TABLE public.mtg_card_trends RENAME TO mtg_card_trends_legacy_20260327';
  END IF;
END $$;

-- Note: intra-legacy FKs (mtg_card_trends.card_id → mtg_cards.id and
-- mtg_daily_prices.card_id → mtg_cards.id) continue to work after
-- rename because PostgreSQL tracks constraints by OID, not by name.
-- The constraints will now report their target table as
-- mtg_cards_legacy_20260327.

-- ─── mtg_sets (NEW canonical set catalogue) ────────────────────────────────
-- One row per Scryfall set (or, later, any other set source). Internal
-- UUID PK; scryfall_id + code are UNIQUE natural keys.

CREATE TABLE IF NOT EXISTS mtg_sets (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scryfall_id      UUID UNIQUE,          -- Scryfall's set object UUID; UNIQUE when populated
  code             TEXT UNIQUE NOT NULL, -- Scryfall's short set code (e.g. 'neo')
  name             TEXT NOT NULL,
  set_type         TEXT,
  released_at      DATE,
  card_count       INTEGER,
  digital          BOOLEAN,
  foil_only        BOOLEAN,
  nonfoil_only     BOOLEAN,
  icon_svg_uri     TEXT,
  scryfall_uri     TEXT,
  parent_set_code  TEXT,
  block            TEXT,
  block_code       TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  mtg_sets IS 'Canonical MTG set catalogue. One row per Scryfall (or future non-Scryfall) set.';
COMMENT ON COLUMN mtg_sets.scryfall_id     IS 'Scryfall set object UUID. UNIQUE when populated. NULL for sets from other sources.';
COMMENT ON COLUMN mtg_sets.code            IS 'Scryfall short code (e.g. neo). UNIQUE + NOT NULL.';
COMMENT ON COLUMN mtg_sets.parent_set_code IS 'Scryfall parent_set_code for promo/token/masterpiece sets. NULL for standalone sets.';
COMMENT ON COLUMN mtg_sets.block           IS 'Human-readable block name (Scryfall.block). NULL when Scryfall omits it.';
COMMENT ON COLUMN mtg_sets.block_code      IS 'Machine-readable block code (Scryfall.block_code). NULL when Scryfall omits it.';

-- ─── mtg_oracle_cards ───────────────────────────────────────────────────────
-- One row per game-rules card identity (Scryfall oracle_id). Reprints of the
-- same card share this row. The internal UUID `id` is what the rest of the
-- MTGPrices model references; `oracle_id` is the external key we use to
-- reconcile against Scryfall.

CREATE TABLE IF NOT EXISTS mtg_oracle_cards (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  oracle_id       UUID UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  mana_cost       TEXT,
  -- Postgres treats "cmc" and "mana_value" interchangeably at the type
  -- level. We name it mana_value because MTG's Comprehensive Rules
  -- renamed CMC → mana value in 2021; ingestion maps Scryfall.cmc into it.
  mana_value      NUMERIC(6, 2),
  type_line       TEXT,
  oracle_text     TEXT,
  power           TEXT,
  toughness       TEXT,
  loyalty         TEXT,
  defense         TEXT,
  colors          TEXT[],
  color_identity  TEXT[],
  keywords        TEXT[],
  produced_mana   TEXT[],
  reserved        BOOLEAN,
  layout          TEXT,
  game_changer    BOOLEAN,
  card_faces      JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  mtg_oracle_cards IS 'Game-rules identity for MTG cards. One row per Scryfall oracle_id. Reprints share this row.';
COMMENT ON COLUMN mtg_oracle_cards.mana_value IS 'Mana value (formerly converted mana cost / CMC). Populated from Scryfall.cmc.';
COMMENT ON COLUMN mtg_oracle_cards.card_faces IS 'Multi-face Oracle data preserved as jsonb for DFC/MDFC/split/adventure layouts.';

-- ─── mtg_printings ──────────────────────────────────────────────────────────
-- One row per Scryfall printing object. Every printing belongs to exactly one
-- oracle_card. Scryfall's printing UUID is exposed as `scryfall_id`, not as
-- the primary key, so the internal MTGPrices identity is decoupled from
-- Scryfall's identifier space.

CREATE TABLE IF NOT EXISTS mtg_printings (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  oracle_card_id     UUID NOT NULL REFERENCES mtg_oracle_cards(id) ON DELETE RESTRICT,
  set_id             UUID NOT NULL REFERENCES mtg_sets(id) ON DELETE RESTRICT,
  scryfall_id        UUID UNIQUE NOT NULL,
  set_code           TEXT NOT NULL,
  collector_number   TEXT,
  lang               TEXT,
  name               TEXT NOT NULL,
  layout             TEXT,
  rarity             TEXT,
  artist             TEXT,
  illustration_id    UUID,
  image_uri          TEXT,
  image_uri_small    TEXT,
  art_crop_uri       TEXT,
  promo              BOOLEAN,
  reprint            BOOLEAN,
  variation          BOOLEAN,
  full_art           BOOLEAN,
  borderless         BOOLEAN,
  textless           BOOLEAN,
  digital            BOOLEAN,
  released_at        DATE,
  scryfall_uri       TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  mtg_printings IS 'One row per Scryfall printing object. Internal UUID PK; scryfall_id is the external Scryfall printing UUID.';
COMMENT ON COLUMN mtg_printings.oracle_card_id IS 'FK to mtg_oracle_cards.id — the game-rules identity this physical printing represents.';
COMMENT ON COLUMN mtg_printings.set_id         IS 'FK to mtg_sets.id — the AUTHORITATIVE relational link to the set.';
COMMENT ON COLUMN mtg_printings.set_code       IS 'Denormalised copy of mtg_sets.code retained for human debugging and queries where the caller only has the Scryfall code. The source of truth is set_id. Ingestion must keep this in sync with mtg_sets.code.';

-- ─── mtg_printing_finishes ──────────────────────────────────────────────────
-- Finish variants of a printing. Storing finish as a TEXT column (not a
-- Postgres ENUM) keeps future finish additions cheap (no ALTER TYPE needed).
-- Current expected values: nonfoil, foil, etched. Future values may include
-- glossy, gilded, textured, oversized, etc.

CREATE TABLE IF NOT EXISTS mtg_printing_finishes (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  printing_id   UUID NOT NULL REFERENCES mtg_printings(id) ON DELETE CASCADE,
  finish        TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (printing_id, finish)
);

COMMENT ON TABLE  mtg_printing_finishes IS 'Finish variants of an MTG printing (nonfoil / foil / etched / …). Price observations attach to (printing, finish).';

-- ─── mtg_oracle_legalities ──────────────────────────────────────────────────
-- Format legality is a game-rules concept, so it lives at Oracle level, not
-- printing level. jsonb stays in legacy mtg_cards for reference but this
-- normalised table is what Deck Builder + AI will query.

CREATE TABLE IF NOT EXISTS mtg_oracle_legalities (
  oracle_card_id  UUID NOT NULL REFERENCES mtg_oracle_cards(id) ON DELETE CASCADE,
  format          TEXT NOT NULL,
  legality        TEXT NOT NULL,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (oracle_card_id, format)
);

COMMENT ON TABLE mtg_oracle_legalities IS 'Normalised per-format legality. Format values follow Scryfall (standard, modern, legacy, vintage, commander, pauper, pioneer, etc.).';

-- ─── mtg_rulings ────────────────────────────────────────────────────────────
-- Authoritative rulings (Wizards / DCI / Scryfall imports). Empty for now;
-- Stage 1B will populate from Scryfall or MTGJSON. Uniqueness on
-- (oracle_card_id, source, published_at, comment_hash) prevents duplicate
-- rulings on repeated imports.

CREATE TABLE IF NOT EXISTS mtg_rulings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  oracle_card_id  UUID NOT NULL REFERENCES mtg_oracle_cards(id) ON DELETE CASCADE,
  source          TEXT NOT NULL,
  published_at    DATE,
  comment         TEXT NOT NULL,
  comment_hash    TEXT GENERATED ALWAYS AS (encode(digest(comment, 'sha256'), 'hex')) STORED,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (oracle_card_id, source, published_at, comment_hash)
);

COMMENT ON TABLE mtg_rulings IS 'Authoritative rulings on a card. comment_hash is a stable dedup key so re-imports do not duplicate.';

-- ─── mtg_external_identifiers ──────────────────────────────────────────────
-- Provider reconciliation table. Scryfall's canonical printing UUID lives
-- directly on mtg_printings.scryfall_id; this table maps OTHER providers'
-- IDs (MTGJSON UUID, TCGplayer product_id, Cardmarket product_id, etc.) to
-- our internal printing.
--
-- Deliberately NOT using the existing Pokemon-oriented provider_card_links
-- table so MTG's reconciliation model can evolve independently.

CREATE TABLE IF NOT EXISTS mtg_external_identifiers (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  printing_id       UUID NOT NULL REFERENCES mtg_printings(id) ON DELETE CASCADE,
  provider          TEXT NOT NULL,
  identifier_type   TEXT NOT NULL,
  identifier_value  TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- One printing may have exactly one (provider, identifier_type) mapping.
  UNIQUE (printing_id, provider, identifier_type),
  -- No two printings share the same (provider, identifier_type, value).
  UNIQUE (provider, identifier_type, identifier_value)
);

COMMENT ON TABLE mtg_external_identifiers IS 'External provider IDs for MTG printings (MTGJSON UUID, TCGplayer product_id, Cardmarket product_id, …). Scryfall printing IDs live on mtg_printings.scryfall_id.';

-- ─── mtg_price_observations ────────────────────────────────────────────────
-- Append-only historical prices. Never UPDATE in normal operation.
--
-- Column semantics — chosen so MTGJSON's multi-provider price structure
-- can be preserved WITHOUT collapsing every observation into a single
-- generic "MTGJSON price". MTGJSON's daily payload is shaped:
--
--   { "paper": { "tcgplayer": { "retail":  { "normal":  { "date": price }},
--                                "buylist": { "foil":    { "date": price }}},
--                "cardmarket": { … },
--                "cardkingdom":{ … }},
--     "mtgo":  { "cardhoarder": { "retail": { "foil": { … }}}}}
--
-- We map that structure into columns as:
--   market              = "paper" | "mtgo"                (channel)
--   provider            = "tcgplayer" | "cardmarket" | "cardkingdom"
--                        | "cardhoarder" | "scryfall" | …
--                         → the UNDERLYING pricing provider / marketplace
--                           the observation was sourced from. Whatever
--                           string MTGJSON (or the future importer) hands
--                           us is preserved verbatim. Not enumerated.
--   ingestion_source    = "mtgjson_all_prices"
--                        | "mtgjson_all_prices_today"
--                        | "scryfall_bulk"
--                        | …
--                         → the DELIVERY / PARSING PIPELINE that produced
--                           the row. Distinct from `provider`.
--   price_type          = "retail" | "buylist" | "market" | …
--                         → the price kind within the provider.
--   finish              (via printing_finish_id → mtg_printing_finishes)
--                         → nonfoil / foil / etched / …
--   currency            = "USD" | "EUR" | "TIX" | …
--   condition           = optional condition qualifier where a provider
--                         quotes prices at a specific condition; NULL
--                         means "provider does not qualify by condition".
--
-- The uniqueness index (functional, defined below) treats NULLs in
-- market / price_type / condition as their empty-string equivalents so
-- append-only invariants hold even when a provider does not populate
-- those dimensions.
--
-- import_run_id is nullable so a future backfill path that predates
-- market_import_runs integration would still land cleanly. Every
-- production import MUST populate import_run_id.

CREATE TABLE IF NOT EXISTS mtg_price_observations (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  printing_finish_id  UUID NOT NULL REFERENCES mtg_printing_finishes(id) ON DELETE RESTRICT,
  observed_on         DATE NOT NULL,
  provider            TEXT NOT NULL,
  ingestion_source    TEXT NOT NULL,
  market              TEXT,
  currency            TEXT NOT NULL,
  price_type          TEXT,
  condition           TEXT,
  price               NUMERIC(14, 4) NOT NULL,
  import_run_id       UUID REFERENCES market_import_runs(id) ON DELETE SET NULL,
  source_reference    TEXT,
  is_anomalous        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  mtg_price_observations IS 'Append-only daily price observations. One row per (printing_finish, date, provider, market, currency, price_type, condition).';
COMMENT ON COLUMN mtg_price_observations.provider          IS 'Underlying pricing provider / marketplace (tcgplayer, cardmarket, cardkingdom, cardhoarder, scryfall, …). Preserved verbatim from the source; NOT enumerated.';
COMMENT ON COLUMN mtg_price_observations.ingestion_source  IS 'Delivery / parsing pipeline that produced this row (e.g. mtgjson_all_prices, mtgjson_all_prices_today, scryfall_bulk). Distinct from provider.';
COMMENT ON COLUMN mtg_price_observations.market            IS 'Channel: paper | mtgo | arena. Nullable when the source does not partition by market.';
COMMENT ON COLUMN mtg_price_observations.price_type        IS 'Price kind within a provider: retail | buylist | market | low | mid | high | …';
COMMENT ON COLUMN mtg_price_observations.condition         IS 'Optional condition qualifier (NM, LP, MP, …) when a provider quotes prices per condition. NULL when unqualified.';
COMMENT ON COLUMN mtg_price_observations.import_run_id     IS 'FK to market_import_runs. Nullable but production imports MUST populate it.';
COMMENT ON COLUMN mtg_price_observations.is_anomalous      IS 'Set TRUE by downstream anomaly detection; never used to filter historical rows out.';

-- Functional unique index that treats NULL market/price_type/condition as
-- their empty-string equivalents so we do not accidentally allow duplicate
-- observations. Postgres unique constraints treat NULL as distinct, which
-- is not what we want here.
CREATE UNIQUE INDEX IF NOT EXISTS mtg_price_observations_unique_key
  ON mtg_price_observations (
    printing_finish_id,
    observed_on,
    provider,
    COALESCE(market, ''),
    currency,
    COALESCE(price_type, ''),
    COALESCE(condition, '')
  );

-- ─── Indexes ────────────────────────────────────────────────────────────────
-- Uniqueness on oracle_id / scryfall_id already gives us those indexes.
-- Additional indexes for the common Stage 1 read paths.

CREATE INDEX IF NOT EXISTS mtg_oracle_cards_name_idx           ON mtg_oracle_cards(name);
CREATE INDEX IF NOT EXISTS mtg_oracle_cards_layout_idx         ON mtg_oracle_cards(layout);

CREATE INDEX IF NOT EXISTS mtg_printings_oracle_card_id_idx    ON mtg_printings(oracle_card_id);
CREATE INDEX IF NOT EXISTS mtg_printings_set_id_idx            ON mtg_printings(set_id);
CREATE INDEX IF NOT EXISTS mtg_printings_set_code_idx          ON mtg_printings(set_code);
CREATE INDEX IF NOT EXISTS mtg_printings_set_collector_idx     ON mtg_printings(set_code, collector_number);
CREATE INDEX IF NOT EXISTS mtg_printings_released_at_idx       ON mtg_printings(released_at);

-- (printing_id, finish) UNIQUE already provides an index on printing_id.

CREATE INDEX IF NOT EXISTS mtg_oracle_legalities_format_legality_idx
  ON mtg_oracle_legalities(format, legality);

-- (provider, identifier_type, identifier_value) UNIQUE already indexes this.

CREATE INDEX IF NOT EXISTS mtg_price_observations_finish_date_idx
  ON mtg_price_observations(printing_finish_id, observed_on);
CREATE INDEX IF NOT EXISTS mtg_price_observations_date_idx
  ON mtg_price_observations(observed_on);
CREATE INDEX IF NOT EXISTS mtg_price_observations_provider_date_idx
  ON mtg_price_observations(provider, observed_on);

-- ─── RLS policies ───────────────────────────────────────────────────────────
-- These are public catalogue / market-data tables. Anonymous and authenticated
-- users may SELECT freely. All writes go through the service-role client
-- (which bypasses RLS entirely); we do NOT define INSERT/UPDATE/DELETE
-- policies for anon / authenticated so those verbs are implicitly denied.

ALTER TABLE mtg_sets                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_oracle_cards         ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_printings            ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_printing_finishes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_oracle_legalities    ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_rulings              ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_external_identifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE mtg_price_observations   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS mtg_sets_read                 ON mtg_sets;
DROP POLICY IF EXISTS mtg_oracle_cards_read         ON mtg_oracle_cards;
DROP POLICY IF EXISTS mtg_printings_read            ON mtg_printings;
DROP POLICY IF EXISTS mtg_printing_finishes_read    ON mtg_printing_finishes;
DROP POLICY IF EXISTS mtg_oracle_legalities_read    ON mtg_oracle_legalities;
DROP POLICY IF EXISTS mtg_rulings_read              ON mtg_rulings;
DROP POLICY IF EXISTS mtg_external_identifiers_read ON mtg_external_identifiers;
DROP POLICY IF EXISTS mtg_price_observations_read   ON mtg_price_observations;

CREATE POLICY mtg_sets_read
  ON mtg_sets                 FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_oracle_cards_read
  ON mtg_oracle_cards         FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_printings_read
  ON mtg_printings            FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_printing_finishes_read
  ON mtg_printing_finishes    FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_oracle_legalities_read
  ON mtg_oracle_legalities    FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_rulings_read
  ON mtg_rulings              FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_external_identifiers_read
  ON mtg_external_identifiers FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY mtg_price_observations_read
  ON mtg_price_observations   FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- SCHEMA-ONLY MIGRATION — no backfill.
-- ============================================================================
-- The legacy tables (mtg_sets, mtg_cards, mtg_daily_prices, mtg_card_trends)
-- are NOT copied into the target tables. All seven target tables are
-- expected to be EMPTY after this migration applies. That is intentional:
--
--   * Stage 1B (Python scraper repo) populates mtg_sets/mtg_oracle_cards/
--     mtg_printings/mtg_printing_finishes/mtg_oracle_legalities from a
--     fresh Scryfall bulk pull.
--   * Stage 1C (Python scraper repo) populates mtg_external_identifiers
--     and mtg_price_observations from fresh MTGJSON downloads
--     (AllIdentifiers / AllPrintings for reconciliation, AllPrices for
--     the previous ~90 days, AllPricesToday appended daily).
--   * mtg_rulings is populated by whichever pipeline delivers
--     authoritative rulings (typically Scryfall).
--
-- Reconciliation across identifier systems must go through the mtg_external
-- _identifiers table (MTGJSON UUID ↔ Scryfall printing ID ↔ marketplace
-- identifiers). Names are NEVER used as the primary reconciliation key.
-- ============================================================================

COMMIT;

-- ============================================================================
-- End of migration. Legacy tables (mtg_sets, mtg_cards, mtg_daily_prices,
-- mtg_card_trends) remain untouched. Zero rows expected in the seven new
-- target tables.
-- ============================================================================
